### ISSUE TITLE
scalasyd presentation?

### ISSUE THREAD

**Issue by arnolddevos** [eli-jordan/eli-jordan.github.io#1]
Life Is A Comonad  would make a good presentation at scalasyd!

**Comment by eli-jordan** [comment]
Thanks @arnolddevos Jed from ScalaSyd pinged me. I'd be happy to present on this topic.

**Comment by arnolddevos** [comment]
Good.  @Scalasyd which would be Charles or Jed asked me to try and reach you too after I commented on your post.
